name: Build
on: [workflow_dispatch]
permissions:
  contents: write
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: fuse
      run: |
          sudo apt-get update
          sudo apt-get -y install libfuse2
    - name: Construct AppDir
      run: make
    - name: Get appimagetool
      run: |
        curl --location -o appimagetool https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
        chmod +x appimagetool
    - name: Make AppImage
      run: ./appimagetool build/anki.AppDir
    - name: Release with Notes
      uses: softprops/action-gh-release@v1
      with:
        tag_name: release
        files: |
          ./Anki-x86_64.AppImage
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload AppImage
      uses: actions/upload-artifact@v1
      with:
        name: Anki-x86_64.AppImage
        path: ./Anki-x86_64.AppImage
